services:
  satisfactory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - 15777:15777/udp
     - 15000:15000/udp
     - 7777:7777/udp
    volumes:
     - /data/satisfactory:/satisfactory/data